name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn clean package -B

      - name: Rename JAR
        run: mv target/Shard-Ruby.jar Shard-Ruby.jar

      - name: Upload Shard-Ruby.jar
        uses: actions/upload-artifact@v4
        with:
          name: Shard-Ruby
          path: Shard-Ruby.jar
